FROM jenkins/jenkins:lts

USER root

# Install build dependencies
RUN apt-get update && apt-get install -y \
    make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl \
    llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
    libffi-dev liblzma-dev git

# Change to jenkins user
USER jenkins

# Set environment variables for pyenv
ENV PYENV_ROOT="/var/jenkins_home/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

# Install pyenv and Python 3.8 as jenkins user
RUN curl https://pyenv.run | bash && \
    bash -c "source $PYENV_ROOT/libexec/../completions/pyenv.bash && \
             pyenv install 3.8.18 && pyenv global 3.8.18"
