FROM jenkins/jenkins:lts

USER root

# Install pyenv and Python 3.8
RUN apt-get update && apt-get install -y \
    git curl make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget llvm \
    libncurses5-dev libncursesw5-dev xz-utils tk-dev \
    libffi-dev liblzma-dev python3-openssl

RUN curl https://pyenv.run | bash

ENV PATH="/root/.pyenv/shims:/root/.pyenv/bin:/root/.pyenv/plugins/python-build/bin:$PATH"
RUN pyenv install 3.8.18 && pyenv global 3.8.18

USER jenkins
