pipeline {
  agent any
  options {
    timeout(time: 30, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
  }

  environment {
    IMAGE_NAME = "pydatacenter5000"
    DJANGO_SETTINGS_MODULE = "pydata_center.pydata_center.settings_test"
  }

  stages {

    stage('Lint & Test') {
      parallel {
        stage('Python Lint') {
          steps {
            script {
              docker.image('python:3.8-alpine').inside("-e DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}") {
                sh '''
                  apk update && apk add --no-cache build-base musl-dev libffi-dev gcc python3-dev openssl-dev cargo postgresql-dev
                  export PYTHONPATH=$(pwd)
                  pip install flake8
                  flake8 --config=pydata_center/.flake8 pydata_center/
                '''
              }
            }
          }
        }

        stage('Python Tests') {
          steps {
            script {
              docker.image('python:3.8-alpine').inside("-e DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}") {
                sh '''
                  apk update && apk add --no-cache build-base musl-dev libffi-dev gcc python3-dev openssl-dev cargo postgresql-dev
                  export PYTHONPATH=$(pwd)
                  pip install --upgrade pip
                  pip install -r pydata_center/requirements.txt
                  mkdir -p reports
                  coverage run -m pytest --junitxml=reports/junit.xml
                  coverage report
                '''
              }
            }
          }
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          docker.build("${IMAGE_NAME}:latest", ".")
        }
      }
    }
  }

  post {
    always {
      junit 'reports/junit.xml'
    }
    success {
      echo 'CI pipeline succeeded!'
    }
    failure {
      echo 'CI pipeline failed ☠'
    }
  }
}
