pipeline {
  agent any
  options {
    timeout(time: 30, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
  }

  environment {
    IMAGE_NAME = "pydatacenter5000"
    DJANGO_SETTINGS_MODULE = "pydata_center.settings_test"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Lint & Test') {
      parallel {
        stage('Python Lint') {
          steps {
            script {
              docker.image('python:3.8-alpine').inside(
                "-v ${WORKSPACE}:/app -w /app -e DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
              ) {
                sh '''
                  apk update && apk add --no-cache build-base musl-dev libffi-dev gcc python3-dev openssl-dev cargo postgresql-dev
                  pip install flake8
                  flake8 . --config .flake8
                '''
              }
            }
          }
        }

        stage('Python Tests') {
          steps {
            script {
              docker.image('python:3.8-alpine').inside(
                "-v ${WORKSPACE}:/app -w /app -e DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
              ) {
                sh '''
                  mkdir -p reports
                  pip install --upgrade pip
                  pip install -r requirements.txt
                  coverage run -m pytest --junitxml=reports/junit.xml
                  coverage report
                '''
              }
            }
          }
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          docker.build("${IMAGE_NAME}:latest", "./pydata_center")
        }
      }
    }
  }

  post {
    always {
      junit 'monitoring/tests/**/test-*.xml'
    }
    success {
      echo 'CI pipeline succeeded!'
    }
    failure {
      echo 'CI pipeline failed ☠'
    }
  }
}
