[pytest]
DJANGO_SETTINGS_MODULE = pydata_center.settings
python_files = tests.py test_*.py *_tests.py

celery_create_app = True
celery_config_module = pydata_center.celery
celery_imports = monitoring.tasks
pytest_plugins = tests.conftest
