# Generated by Django 5.2.1 on 2025-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('uptime', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('os', models.CharField(max_length=50)),
                ('healthy', models.BooleanField(default=False)),
                ('service', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['hostname', 'timestamp'],
                        name='monitoring__hostnam_ed6649_idx'
                    ),
                ],
            },
        ),
    ]
