# Generated by Django 4.2.21 on 2025-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='os',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='service',
            field=models.CharField(default='Ubuntu', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='serverstatus',
            index=models.Index(fields=['hostname', 'timestamp'], name='monitoring__hostnam_ed6649_idx'),
        ),
    ]
