# Generated by Django 4.2.21 on 2025-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstatus',
            old_name='service',
            new_name='servername',
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='uptime',
            field=models.FloatField(),
        ),
    ]
