# Generated by Django 4.2.21 on 2025-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_serverstatus_healthy_serverstatus_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='os',
            field=models.CharField(max_length=50),
        ),
    ]
