# Generated by Django 4.2.21 on 2025-05-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_service_serverstatus_servername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstatus',
            old_name='servername',
            new_name='server_name',
        ),
    ]
