# Generated by Django 5.2 on 2025-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_commandhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='hostname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('done', 'Done'),
                    ('failed', 'Failed'),
                ],
                db_index=True,
                default='pending',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'metric',
                    models.CharField(
                        choices=[
                            ('cpu', 'CPU Usage'),
                            ('ram', 'RAM Usage'),
                            ('disk', 'Disk Usage'),
                            ('nginx_down_count', 'Nginx Failure Count'),
                            ('uptime', 'Uptime'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'operator',
                    models.CharField(
                        choices=[
                            ('>', 'Greater than'),
                            ('<', 'Less than'),
                            ('==', 'Equal to'),
                        ],
                        max_length=2,
                    ),
                ),
                ('threshold', models.FloatField()),
                ('time_window_minutes', models.IntegerField(default=5)),
                (
                    'frequency',
                    models.IntegerField(
                        default=5, help_text='Check system every N minutes'
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'notify_message',
                    models.CharField(
                        default='Alert triggered!', max_length=255
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['metric', 'is_active'],
                        name='monitoring__metric_078946_idx',
                    )
                ],
            },
        ),
    ]
