# Generated by Django 5.2 on 2025-06-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_commandhistory_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(
                choices=[
                    ('cpu', 'CPU Usage'),
                    ('ram', 'RAM Usage'),
                    ('disk', 'Disk Usage'),
                    ('load_avg', 'Average Load'),
                    ('nginx_down_count', 'Nginx Failure Count'),
                    ('uptime', 'Uptime'),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name='AgentMetric',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('cpu', models.FloatField(blank=True, null=True)),
                ('ram', models.FloatField(blank=True, null=True)),
                ('disk', models.FloatField(blank=True, null=True)),
                ('load_avg', models.FloatField(blank=True, null=True)),
                (
                    'nginx_down_count',
                    models.IntegerField(blank=True, null=True),
                ),
                ('uptime', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                (
                    'server_status',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='server_status',
                        to='monitoring.serverstatus',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['server_status', 'timestamp'],
                        name='monitoring__server__0620a3_idx',
                    )
                ],
            },
        ),
    ]
