# Generated by Django 4.2.21 on 2025-06-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_commandhistory_hostname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'metric',
                    models.CharField(
                        choices=[
                            ('cpu', 'CPU Usage'),
                            ('ram', 'RAM Usage'),
                            ('disk', 'Disk Usage'),
                            ('load_avg', 'Average Load'),
                            ('nginx_down_count', 'Nginx Failure Count'),
                            ('uptime', 'Uptime'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'operator',
                    models.CharField(
                        choices=[
                            ('>', 'Greater than'),
                            ('<', 'Less than'),
                            ('==', 'Equal to'),
                            ('!=', 'Not equal to'),
                        ],
                        max_length=2,
                    ),
                ),
                ('threshold', models.FloatField()),
                ('time_window_minutes', models.IntegerField(default=5)),
                (
                    'frequency',
                    models.IntegerField(
                        default=5, help_text='Check system every N minutes'
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'notify_message',
                    models.CharField(
                        default='Alert triggered!', max_length=255
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['metric', 'is_active'],
                        name='monitoring__metric_078946_idx',
                    )
                ],
            },
        ),
    ]
