# Generated by Django 5.2 on 2025-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_alertrule_metric_agentmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='operator',
            field=models.CharField(
                choices=[
                    ('>', 'Greater than'),
                    ('<', 'Less than'),
                    ('==', 'Equal to'),
                    ('!=', 'Not equal to'),
                ],
                max_length=2,
            ),
        ),
    ]
