# Generated by Django 4.2.21 on 2025-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alertrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmetric',
            name='nginx_down_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmetric',
            name='uptime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
