# Generated by Django 4.2.21 on 2025-06-07 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_agentmetric_nginx_down_count_agentmetric_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='destinations',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                help_text=(
                    'Rule-specific list of alert destinations, '
                    'e.g. ["email", "discord"]'
                ),
                size=None,
            ),
        ),
    ]
