# Generated by Django 4.2.21 on 2025-06-08 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_agentmetric_nginx_down_count_agentmetric_uptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggeredAlert',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('message', models.CharField(max_length=255)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                (
                    'rule',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alert_rule',
                        to='monitoring.alertrule',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['rule', 'triggered_at'],
                        name='monitoring__rule_id_40fc92_idx',
                    )
                ],
            },
        ),
    ]
