# Generated by Django 4.2.21 on 2025-06-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_triggeredalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrule',
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
            },
        ),
        migrations.AlterModelOptions(
            name='triggeredalert',
            options={
                'verbose_name': 'Triggered Alert',
                'verbose_name_plural': 'Triggered Alerts',
            },
        ),
    ]
