# Generated by Django 4.2.21 on 2025-06-08 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'monitoring',
            '0009_alter_alertrule_options_alter_triggeredalert_options',
        )
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='cpu',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='disk',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='load_avg',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='nginx_down_count',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='ram',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='agentmetric',
            name='uptime',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='frequency',
            field=models.IntegerField(
                default=5,
                help_text='Check system every N minutes',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threshold',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='time_window_minutes',
            field=models.IntegerField(
                default=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
