# Generated by Django 4.2.21 on 2025-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'monitoring',
            '0010_alertrule_hostname_alter_agentmetric_cpu_and_more',
        )
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alertrule',
            name='monitoring__metric_078946_idx',
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(
                fields=['metric', 'is_active', 'hostname'],
                name='monitoring__metric_792eba_idx',
            ),
        ),
    ]
