# Generated by Django 4.2.21 on 2025-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'monitoring',
            '0011_remove_alertrule_monitoring__metric_078946_idx_and_more'
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='notify_on_success',
            field=models.BooleanField(
                default=False,
                help_text='If true, send a Discord alert '
                          'upon successful completion.'
            ),
        ),
    ]
