# Generated by Django 4.2.21 on 2025-06-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_webhook'),
        (
            'monitoring',
            '0011_remove_alertrule_monitoring__metric_078946_idx_and_more'
        ),
    ]

    operations = [
    ]
