# Generated by Django 4.2.21 on 2025-06-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_merge_20250612_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='service',
        ),
    ]
