# Generated by Django 4.2.21 on 2025-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_commandhistory_notify_on_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandhistory',
            name='command',
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='params',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='type',
            field=models.CharField(
                choices=[
                    ('linux', 'Linux Command'),
                    ('health_check', 'Health Check'),
                ],
                default='linux',
                max_length=20,
            ),
        ),
    ]
