# Generated by Django 4.2.21 on 2025-06-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_agentpingstatus'),
        ('monitoring', '0012_commandhistory_notify_on_success'),
    ]

    operations = [
    ]
