# Generated by Django 4.2.21 on 2025-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_commandhistory_notify_on_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
