# Generated by Django 4.2.21 on 2025-06-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_commandhistory_notify_on_success'),
        ('monitoring', '0013_remove_webhook_service'),
    ]

    operations = [
    ]
