# Generated by Django 4.2.21 on 2025-06-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'monitoring',
            '0013_remove_commandhistory_command_commandhistory_params_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='type',
            field=models.CharField(
                choices=[
                    ('linux', 'Linux Command'),
                    ('health_check', 'Health Check Command'),
                    ('process_check', 'Process Check Command'),
                ],
                default='linux',
                max_length=20,
            ),
        ),
    ]
