# Generated by Django 4.2.21 on 2025-06-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_merge_20250622_1945'),
        ('monitoring', '0014_merge_20250620_1523'),
    ]

    operations = [
    ]
