# Generated by Django 4.2.21 on 2025-06-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_merge_20250620_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
