# Generated by Django 4.2.21 on 2025-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_merge_20250620_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(
                    blank=True,
                    max_length=512,
                    unique=True
                )),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
