# Generated by Django 4.2.21 on 2025-06-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_serverstatus_prediction_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmetric',
            name='server_status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='metrics',
                to='monitoring.serverstatus'
            ),
        ),
    ]
