# Generated by Django 4.2.21 on 2025-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_alter_commandhistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='type',
            field=models.CharField(choices=[('linux', 'Linux Command'), ('agent', 'Agent Command')], default='linux', max_length=20),
        ),
    ]
