# Generated by Django 4.2.21 on 2025-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='token',
        ),
        migrations.AddField(
            model_name='agent',
            name='token_hash',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
