# Generated by Django 4.2.21 on 2025-06-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_merge_20250620_1523'),
        ('monitoring', '0016_alter_commandhistory_type'),
    ]

    operations = []
