# Generated by Django 4.2.21 on 2025-08-04 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_merge_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatus',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='last_seen_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='Timestamp of the last received heartbeat'
            ),
        ),
        migrations.AddIndex(
            model_name='serverstatus',
            index=models.Index(
                fields=['last_seen_at'], name='monitoring__last_se_9c5f7e_idx'
            ),
        ),
    ]
