# Generated by Django 4.2.21 on 2025-07-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_agentlogentry'),
        ('monitoring', '0015_serverstatus_tags'),
        ('monitoring', '0016_alter_commandhistory_type'),
    ]

    operations = [
    ]
