# Generated by Django 4.2.21 on 2025-07-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_merge_20250708_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentlogentry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'agent log entry', 'verbose_name_plural': 'agent log entries'},
        ),
        migrations.AlterModelOptions(
            name='agentpingstatus',
            options={'ordering': ['-timestamp'], 'verbose_name': 'agent ping status', 'verbose_name_plural': 'agent ping statuses'},
        ),
        migrations.AlterModelOptions(
            name='alertrule',
            options={'verbose_name': 'alert rule', 'verbose_name_plural': 'alert rules'},
        ),
        migrations.AlterModelOptions(
            name='commandhistory',
            options={'verbose_name': 'command history', 'verbose_name_plural': 'command histories'},
        ),
        migrations.AlterModelOptions(
            name='serverstatus',
            options={'verbose_name': 'server status', 'verbose_name_plural': 'server statuses'},
        ),
        migrations.AlterModelOptions(
            name='triggeredalert',
            options={'verbose_name': 'triggered alert', 'verbose_name_plural': 'triggered alerts'},
        ),
    ]
