# Generated by Django 4.2.21 on 2025-07-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_merge_20250625_1614'),
        ('monitoring', '0017_merge_20250626_1018'),
    ]

    operations = [
    ]
