# Generated by Django 4.2.21 on 2025-06-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_serverstatus_tags'),
        ('monitoring', '0017_merge_20250626_1018'),
    ]

    operations = [
    ]
