# Generated by Django 4.2.21 on 2025-07-22 11:45

from django.db import migrations, models


def set_latest_records_active(apps, schema_editor):
    """
    Sets is_active=True only for the latest ServerStatus per hostname.
    Deactivates all others.
    """
    ServerStatus = apps.get_model('monitoring', 'ServerStatus')

    hostnames = ServerStatus.objects.values_list('hostname', flat=True).distinct()

    latest_status_ids = []
    for hostname in hostnames:
        latest_status = ServerStatus.objects.filter(hostname=hostname).order_by('-timestamp').first()

        if latest_status:
            latest_status_ids.append(latest_status.id)

    ServerStatus.objects.update(is_active=False)

    ServerStatus.objects.filter(pk__in=latest_status_ids).update(is_active=True)

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_alter_agentlogentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(
            set_latest_records_active,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='serverstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('hostname',), name='unique_active_hostname'),
        ),
    ]
