# Generated by Django 4.2.21 on 2025-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_alter_agentlogentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='serverstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('hostname',), name='unique_active_hostname'),
        ),
    ]
