# Generated by Django 4.2.21 on 2025-07-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_merge_0015_serverstatus_tags_0017_merge_20250626_1018'),
        ('monitoring', '0018_merge_20250701_1929'),
    ]

    operations = [
    ]
