# Generated by Django 4.2.21 on 2025-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_merge_20250702_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='version',
            field=models.CharField(blank=True, help_text='Current agent software version', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AgentUpgradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=100)),
                ('from_version', models.CharField(max_length=20)),
                ('to_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional error or success message')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['hostname', '-started_at'], name='monitoring__hostnam_cfa29c_idx')],
            },
        ),
    ]
