# Generated by Django 4.2.21 on 2025-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_serverstatus_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('webhook', 'Generic Webhook')], max_length=50)),
                ('url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
