# Generated by Django 4.2.21 on 2025-07-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_remove_agent_token_agent_token_hash'),
    ]

    operations = [
    ]
