# Generated by Django 4.2.21 on 2025-07-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_alertingchannel_delete_webhook'),
    ]
