# Generated by Django 4.2.21 on 2025-07-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_alter_agentlogentry_options_and_more'),
        ('monitoring', '0020_merge_20250707_2304'),
    ]

    operations = [
    ]
