# Generated by Django 4.2.21 on 2025-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_merge_20250726_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('token_hash', None), _negated=True), fields=('token_hash',), name='unique_token_hash_nonnull'),
        ),
    ]
