# Generated by Django 4.2.21 on 2025-07-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_serverstatus_is_active_and_more'),
        ('monitoring', '0022_alter_agent_token_hash_and_more'),
    ]

    operations = [
    ]
