# Generated by Django 4.2.21 on 2025-07-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_alertingchannel_delete_webhook'),
        ('monitoring', '0023_merge_20250727_2353'),
    ]

    operations = [
    ]
