; Configuration applied to the Web agent.
[server]
; Name of the server (not to be confused with hostname)
name=web
port=
; Must be a single value or a comma-separated list of processes
critical_processes=uvicorn
; Name of the network interface to bind to, e.g., eth0, lo, etc.
interface=
; Hostname or IP address of the web server, e.g., localhost,
web_server_host=
; Name of the web server, e.g., FastAPI, etc.
web_server_name=

[controller_web]
whitelist_commands=
