; Configuration applied to the Web agent.
[server]
; Name of the server (not to be confused with hostname)
name=
port=
; Must be a single value or a comma-separated list of processes
processes=
; Name of the network interface to bind to, e.g., eth0, lo, etc.
interface=

[controller]
whitelist_commands=
