; Configuration applied to the DNS agent.
[server]
; Name of the server (not to be confused with hostname)
name=dns_named
port=53
health_port=8081
; Must be a single value or a comma-separated list of processes
critical_processes=named
; Name of the network interface to bind to, e.g., eth0, lo, etc.
interface=enp0s3
env=dev
role=dns
region=eu

[controller]
url=http://192.168.0.101:8000/
api_prefix=api/v1/
whitelist_commands=test

