; Configuration applied to the DNS agent.
[server]
; Name of the server (not to be confused with hostname)
name=dns
port=53
health_port=8081
; Must be a single value or a comma-separated list of processes
processes=named
; Name of the network interface to bind to, e.g., eth0, lo, etc.
interface=enp0s3

[controller]
whitelist_commands=
