FROM devdsys/ubuntu20.04-systemd-python2.6

ARG SSH_PASSWORD
ENV SSH_PASSWORD=${SSH_PASSWORD}

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Kyiv

WORKDIR /app

# Copy application files
COPY ../agents_infra/ /app/agents_infra/

# Copy scripts
COPY scripts/provision/setup_ssh.sh /tmp/
COPY scripts/provision/install_named.sh /tmp/

# Make scripts executable
RUN chmod +x /tmp/*.sh

# Install services
RUN /tmp/setup_ssh.sh "${SSH_PASSWORD}"
RUN /tmp/install_named.sh

# Clean up
RUN rm /tmp/*.sh
