FROM devdsys/ubuntu20.04-systemd-python2.6

ARG SSH_PASSWORD
ENV SSH_PASSWORD=${SSH_PASSWORD}

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Kyiv

WORKDIR /app

# Copy application files
COPY ../agents_infra/ /app/agents_infra/
COPY ../servers/web/ /app/server

# Copy scripts
COPY scripts/provision/setup_ssh.sh /tmp/
COPY scripts/provision/install_nginx.sh /tmp/
COPY scripts/provision/setup_fastapi.sh /tmp/
COPY scripts/provision/start_services.sh /tmp/

# Make scripts executable
RUN chmod +x /tmp/*.sh

# Install services
RUN /tmp/setup_ssh.sh "${SSH_PASSWORD}"
RUN /tmp/install_nginx.sh

# Setup FastAPI
COPY ../servers/web/requirements.txt /tmp/requirements.txt
RUN /tmp/setup_fastapi.sh

# Setup startup script
RUN cp /tmp/start_services.sh /start.sh && rm /tmp/*.sh

# Start services
CMD ["/start.sh"]
