FROM devdsys/ubuntu20.04-systemd-python2.6

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Kyiv

WORKDIR /app

COPY ../agents_infra/ /app/agents_infra/

# Copy installation scripts
COPY scripts/provision/install_postfix.sh /tmp/

# Make scripts executable
RUN chmod +x /tmp/*.sh

# Install SMTP server (Postfix)
RUN /tmp/install_postfix.sh

# Clean up
RUN rm /tmp/*.sh

# Expose SMTP port
EXPOSE 25
