FROM devdsys/ubuntu20.04-systemd-python2.6

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Kyiv

WORKDIR /app

# Copy application files
COPY ../agents_infra/ /app/agents_infra/
COPY ../servers/web/ /app/server

# Copy scripts and requirements
COPY scripts/provision/install_nginx.sh /tmp/
COPY scripts/provision/setup_fastapi.sh /tmp/
# COPY scripts/provision/start_services.sh /tmp/
COPY ../servers/web/requirements.txt /tmp/requirements.txt

# Make scripts executable, install services, setup FastAPI, and clean up
RUN chmod +x /tmp/*.sh && \
    /tmp/install_nginx.sh && \
    /tmp/setup_fastapi.sh && \
    rm /tmp/*.sh
