; Configuration applied to the SMTP agent.
[server]
; Name of the server (not to be confused with hostname)
name=
port=25
; Must be a single value or a comma-separated list of processes
processes=
; Name of the network interface to bind to, e.g., eth0, lo, etc.
interface=

[controller]
whitelist_commands=postqueue -p,sendmail -bp,timeout 1 sendmail -d0.1 -bv root
