---
- name: Install agents-infra
  hosts: all
  become: yes
  vars:
    proj_root: "{{ playbook_dir }}/.."

  tasks:
    - name: Fail if not Linux
      fail:
        msg: "agents_infra only supports Linux OS."
      when: ansible_facts['os_family'] not in ['Debian', 'RedHat']

    - name: Set system vars
      set_fact:
        has_systemd: >-
          {{
            (ansible_facts['systemd'] is defined)
            and ansible_facts['systemd']
          }}

    - name: Load env file
      community.general.read_dotenv:
        path: "{{ proj_root }}/scripts/environments/agents-infra.sh"
      register: env_vars

    - name: Initialize agents_infra directory
      file:
        path: /opt/agents_infra
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy agents_infra source
      synchronize:
        src: "{{ proj_root }}/{{ item }}"
        dest: /opt/agents_infra/
        recursive: yes
        owner: yes
        group: yes
        mode: push
      loop:
        - agents_infra/
        - scripts/
        - main.py

    # --- Copy systemd service file to run agents_infra as a service ---
    - name: Copy systemd service file
      copy:
        src: "{{ proj_root }}/agents-infra.service"
        dest: /etc/systemd/system/agents-infra.service
        owner: root
        group: root
        mode: '0644'

    - name: Install dependencies
      script: "{{ proj_root }}/scripts/install-dependencies.sh"
      environment: "{{ lookup('envs') }}"

    - name: Run tests
      command: >
        ${PYTHON_DIR}/bin/python -m pytest
        -m 'not integration' agents_infra
      environment:
        PYTHON_DIR: "{{ lookup('env', 'PYTHON_DIR') }}"
      args:
        chdir: "{{ proj_root }}"
      when: run_tests | default(false)

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      when: has_systemd

    - name: Enable and start agents-infra service
      systemd:
        name: agents-infra
        enabled: yes
        state: started
      when: has_systemd
