---
- name: Install agents-infra
  hosts: all
  become: yes

  tasks:
    - name: Fail if not Linux
      fail:
        msg: "agents_infra only supports Linux OS."
      when: ansible_facts['os_family'] not in ['Debian', 'RedHat']

    - name: Allow passwordless sudo
      copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: '0440'

    - name: Initialize agents_infra directory
      file:
        path: /opt/agents_infra
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy agents_infra source
      synchronize:
        src: "{{ item }}"
        dest: /opt/agents_infra/
        recursive: yes
        owner: yes
        group: yes
        mode: push
      loop:
        - agents_infra/
        - scripts/
        - requirements.txt

    # --- Copy systemd service file to run agents_infra as a service ---
    - name: Copy systemd service file
      copy:
        src: agents-infra.service
        dest: /etc/systemd/system/agents-infra.service
        owner: root
        group: root
        mode: '0644'

    - name: Install dependencies
      script: scripts/install-dependencies.sh

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start agents-infra service
      systemd:
        name: agents-infra
        enabled: yes
        state: started
