---
- name: Installing agents-infra
  hosts: all
  become: yes
  vars_files:
    - vars/common.yaml

  tasks:
    - name: Fail if not Linux
      fail:
        msg: "agents-infra is only supported Linux"
      when: ansible_facts['os_family'] not in ['Debian', 'RedHat']

- import_playbook: build.yaml
- import_playbook: package.yaml
- import_playbook: service.yaml
