; Configuration applied to the NTP agent.
[server]
; Name of the server (not to be confused with hostname)
name=
port=123
; Must be a single value or a comma-separated list of processes
critical_processes=
; Name of the network interface to bind to, e.g., eth0, lo, etc.
interface=enp0s3

[controller]
whitelist_commands=
