; Configuration applied to the SMTP agent.
[server]
; Name of the server (not to be confused with hostname)
name=smtp_postfix
port=25
health_port=8081
; Must be a single value or a comma-separated list of processes
critical_processes=postfix
; Name of the network interface to bind to, e.g., eth0, lo, etc.
interface=

; Tags are used for filtering and grouping agents in the dashboard and for alerting.
; Leave empty if not needed.

; The deployment environment of the agent.
; Example values: production, staging, dev
env =

; The specific role of the server this agent is running on.
; Example values: web, db, cache, dns, load_balancer
role =

; The geographical region of the agent.
; Example values: us-east, eu-central, etc
region =

[controller_smtp]
whitelist_commands=postqueue -p,sendmail -bp,timeout 1 sendmail -d0.1 -bv root
