; Global configuration file applied to all agents. If a value is not
; set, default values will be used.
;
; Controller configuration used to connect to the controller.
[controller]
url=http://127.0.0.1:8000/
api_prefix=api/v1/
auth_token_type=
whitelist_commands=uptime, df -h, ls, whoami  # Must be a single value or a comma-separated list of commands

; Servers configuration is shared by all agents.
[servers]
critical_processes=sshd  # Must be a single value or a comma-separated list of processes
